services:
  lb:
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "30MB"

  api1:
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"

  api2:
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"
